@startuml

package domain {
    package model {

        enum 駅
        package ticket {
            class 乗車券
            class 特急券
        }
        package fare {
            class 運賃
            class 指定席ひかり料金
            class のぞみ割り増し料金
        }
        class 利用日
        class 距離
        class 人数
        enum 大人子供
    }

    package service {
        class 料金計算
        class 特急料金計算

        class 往復判定
        class 距離判定
        class 団体判定
        class 自由席判定
    }
}

package api {
}

class 乗車券 <<Entity>> {
    - ID
    - 乗車駅 : 駅
    - 降車駅 : 駅
    - 利用日
    - 大人子供
}
class 特急券 <<Entity>> {
    - ID
    - 乗車駅 : 駅
    - 降車駅 : 駅
    - 利用日
    - 大人子供
}
enum 駅 <<区分オブジェクト>> {
    東京
    新大阪
    姫路
    --
    - 運賃
    - 指定席ひかり料金
    - のぞみ割り増し料金
    - 距離
}
class 運賃 {
    - 運賃 : int
}
class 指定席ひかり料金 {
    - 指定席ひかり料金 : int
}
class のぞみ割り増し料金 {
    - 料金 :int
}
class 距離 {
    - キロメートル : int
}
class 人数 {
    - 大人人数 : int
    - 子供人数 : int
}
enum 大人子供 {
    大人
    子供
}
class 料金計算 {
    int
}
class 利用日 {
    LocalDate
}

@enduml