@startuml

package domain {
    package model {

        class 申し込みフォーム
        enum 駅
        package fare {
            class 運賃
            class 指定席ひかり料金
            class のぞみ割り増し料金
        }
        class 利用日
        class 距離
        enum 人数
        class 片道往復
        enum 特急利用
    }

}

package application {
    package service {
        class 料金計算
        class 特急料金計算

        class 往復判定
        class 距離判定
        class 団体判定
        class 自由席判定
    }
}

package api {
}

class 申し込みフォーム {
    - 乗車駅 : 駅
    - 降車駅 : 駅
    - 利用日 : LocalDate
    - 片道往復
    - 人数
    - 特急利用
}
enum 駅 <<区分オブジェクト>> {
    東京
    新大阪
    姫路
    --
    - 運賃
    - 指定席ひかり料金
    - のぞみ割り増し料金
    - 距離
}
class 運賃 {
    - 運賃 : int
}
enum 特急利用 {
    利用しない
    ひかり指定席
    のぞみ指定席
    自由席
}
class 指定席ひかり料金 {
    - 指定席ひかり料金 : int
}
class のぞみ割り増し料金 {
    - 料金 :int
}
class 距離 {
    - キロメートル : int
}
enum 人数 {
    18才以上
    18才未満
    --
    人数 : int
}
class 片道往復 {
    is片道 : boolean
}
class 料金計算 {
    int
    + 料金計算(申し込みフォーム) : int
}
class 利用日 {
    LocalDate
}

@enduml